In [1]:
import pandas as pd
import random
from pathlib import Path

In [2]:
DATA_PATH = r"C:\Users\Jasmin Babariya\Downloads\immverse.ai\Task\Data\processed\cleaned_dataset.csv"

df = pd.read_csv(DATA_PATH)

print(df.shape)
df.head()

(657, 4)

,unique_key,sanskrit_data,translation,document
0,1,धृतराष्ट्र उवाचधर्मक्षेत्रे कुरुक्षेत्रे समवेत...,Bhagavad-gītā is the widely read theistic scie...,Verse ID: 1\n\nSanskrit:\nधृतराष्ट्र उवाचधर्मक...
1,2,सञ्जय उवाचदृष्ट्वा तु पाण्डवानीकं व्यूढं दुर्य...,Dhṛtarāṣṭra was blind from birth. Unfortunatel...,Verse ID: 2\n\nSanskrit:\nसञ्जय उवाचदृष्ट्वा त...
2,3,पश्यैतां पाण्डुपुत्राणामाचार्य महतीं चमूम् ।व्...,"Duryodhana, a great diplomat, wanted to point ...",Verse ID: 3\n\nSanskrit:\nपश्यैतां पाण्डुपुत्र...
3,4,अत्र श‍ूरा महेष्वासा भीमार्जुनसमा युधि ।युयुधा...,Even though Dhṛṣṭadyumna was not a very import...,Verse ID: 4\n\nSanskrit:\nअत्र श‍ूरा महेष्वासा...
4,5,धृष्टकेतुश्चेकितानः काशिराजश्च वीर्यवान् ।पुरु...,"There are also great heroic, powerful fighters...",Verse ID: 5\n\nSanskrit:\nधृष्टकेतुश्चेकितानः ...

In [3]:
df.shape

(657, 4)

In [4]:
print(df.columns.tolist())

['unique_key', 'sanskrit_data', 'translation', 'document']

In [5]:
def generate_queries(translation):

    queries = []

    translation = str(translation)

    first_sentence = translation.split(".")[0]

    queries.append(first_sentence)

    queries.append("Explain this verse")

    queries.append("Meaning of this verse")

    queries.append("What does this verse teach?")

    queries.append("Summary of this verse")

    queries.append("Explain the philosophy")

    queries.append("Give interpretation")

    return list(set(queries))

In [6]:
pairs = []

for _, row in df.iterrows():

    verse = row["unique_key"]
    sanskrit = row["sanskrit_data"]
    translation = row["translation"]
    document = row["document"]

    # English Queries
    english_queries = [
        f"What is explained in verse {verse}?",
        f"What does this verse say?",
        f"Explain verse {verse}",
        f"Meaning of verse {verse}",
        translation[:120]
    ]

    for q in english_queries:
        pairs.append({
            "query": q,
            "document": document,
            "label": 1
        })

    # Sanskrit Query
    pairs.append({
        "query": sanskrit,
        "document": document,
        "label": 1
    })

pairs_df = pd.DataFrame(pairs)

In [7]:
print(pairs_df.shape)

pairs_df.head()

(3942, 3)

,query,document,label
0,What is explained in verse 1?,Verse ID: 1\n\nSanskrit:\nधृतराष्ट्र उवाचधर्मक...,1
1,What does this verse say?,Verse ID: 1\n\nSanskrit:\nधृतराष्ट्र उवाचधर्मक...,1
2,Explain verse 1,Verse ID: 1\n\nSanskrit:\nधृतराष्ट्र उवाचधर्मक...,1
3,Meaning of verse 1,Verse ID: 1\n\nSanskrit:\nधृतराष्ट्र उवाचधर्मक...,1
4,Bhagavad-gītā is the widely read theistic scie...,Verse ID: 1\n\nSanskrit:\nधृतराष्ट्र उवाचधर्मक...,1

In [8]:
pairs_df = pairs_df.sample(frac=1, random_state=42).reset_index(drop=True)

pairs_df.head()

,query,document,label
0,What does this verse say?,Verse ID: 137\n\nSanskrit:\nप्रकृतेः क्रियमाणा...,1
1,Explain verse 137,Verse ID: 137\n\nSanskrit:\nप्रकृतेः क्रियमाणा...,1
2,Explain verse 326,Verse ID: 326\n\nSanskrit:\nमया ततमिदं सर्वं ज...,1
3,What does this verse say?,Verse ID: 547\n\nSanskrit:\nअनेकचित्तविभ्रान्त...,1
4,एतान्यपि तु कर्माणि सङ्गं त्यक्त्वा फलानि च ।क...,Verse ID: 587\n\nSanskrit:\nएतान्यपि तु कर्माण...,1

In [9]:
SAVE_PATH = r"C:\Users\Jasmin Babariya\Downloads\immverse.ai\Task\Data\Training\query_pairs.csv"

Path("../data/training").mkdir(parents=True, exist_ok=True)

pairs_df.to_csv(
    SAVE_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("Saved to")

print(SAVE_PATH)

Saved to
C:\Users\Jasmin Babariya\Downloads\immverse.ai\Task\Data\Training\query_pairs.csv

In [10]:
check = pd.read_csv(SAVE_PATH)

print(check.shape)

check.head(10)

(3942, 3)

,query,document,label
0,What does this verse say?,Verse ID: 137\n\nSanskrit:\nप्रकृतेः क्रियमाणा...,1
1,Explain verse 137,Verse ID: 137\n\nSanskrit:\nप्रकृतेः क्रियमाणा...,1
2,Explain verse 326,Verse ID: 326\n\nSanskrit:\nमया ततमिदं सर्वं ज...,1
3,What does this verse say?,Verse ID: 547\n\nSanskrit:\nअनेकचित्तविभ्रान्त...,1
4,एतान्यपि तु कर्माणि सङ्गं त्यक्त्वा फलानि च ।क...,Verse ID: 587\n\nSanskrit:\nएतान्यपि तु कर्माण...,1
5,What is explained in verse 179?,Verse ID: 179\n\nSanskrit:\nश्रोत्रादीनीन्द्रि...,1
6,Meaning of verse 535,Verse ID: 535\n\nSanskrit:\nयो मामेवमसम्मूढो ज...,1
7,What does this verse say?,Verse ID: 562\n\nSanskrit:\nआयु:सत्त्वबलारोग्य...,1
8,What is explained in verse 60?,Verse ID: 60\n\nSanskrit:\nवेदाविनाशिनं नित्यं...,1
9,What is explained in verse 68?,Verse ID: 68\n\nSanskrit:\nआश्चर्यवत्पश्यति कश...,1